# Copyright 2024 -- CONTRIBUTORS. See LICENSE.

load("@lib//bazel:copts.bzl", "COPTS")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hello",
    srcs = ["hello.cpp"],
    copts = COPTS,
    deps = [
        "//engine:glfw_window",
        "//engine:render",
        "//engine:resource",
        "//engine:surface_render",
        "//shaders",
    ],
)
