load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

package(default_visibility = ["//visibility:public"])

#-------------------------------------------------------------------------------

cc_library(
    name = "shaders",
    hdrs = [
      "shaders.hpp", 
      "hello_triangle.vert.spv.inl", 
      "hello_triangle.frag.spv.inl"
    ],
)

